### ISSUE TITLE
Uptime "local variable 'days' referenced before assignment"

### ISSUE THREAD

**Issue by DrownNotably** [Phate6660/pyfetch#1]
Any uptime less than a day results in an error.

**Comment by Phate6660** [comment]
Oops, just meant to reference the issue, not close it.

**Comment by tobyWorland** [comment]
All good!
dbe86321f8e65a1024afe5de2e82c463b7769119

**Comment by DrownNotably** [comment]
All good!
dbe86321f8e65a1024afe5de2e82c463b7769119

**Comment by Phate6660** [comment]
Nice.
